name: CI/CD - Express TS to cPanel via SSH

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies & Build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Build Files to Server
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            dist/ \
            package.json \
            package-lock.json \
            .env \
            ${{ secrets.FTP_USERNAME }}@${{ secrets.SSH_HOST }}:~/base_api/

      - name: Restart Node.js App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/base_api
            npm install --legacy-peer-deps --production
            mkdir -p tmp
            touch tmp/restart.txt
          EOF
